### PR TITLE
Added new local scanner for RDP users

### PR DESCRIPTION
**Pull request by B1t0n**
An additional local scanner that acts as the local Administrators scanner but for local "Remote Desktop Users" group. Can be useful when stuck without administrative access on other endpoints

### CODE REVIEW

**Comment by vletoux** [comment]
I finally read your PR. You have basically copied the 2 files from the local admin scanner and duplicated the code. This is a problem for the maintenance because it has to be maintained twice.
You should have discuss with me first before submitting the PR.

If you want to adapt the local admin scanner, I suggest you combine two Sam calls and add a column in the header to specify the group enumerated rather than adding a second scanner.
That way, you can scan both admin & rdp user in a single scan (and thus divide the both scans time by 2).

What do you think about this ?

**Comment by B1t0n** [comment]
Thanks for the feedback, you are actually right. 
If so, what do you think about creating a sub-menu for the local-scanner and allow the user to pick which local groups he would like to scan in a single scan (not only Admin and RDP). 
It can be presented in a menu that the user will be able to pick up from in a comma separated style:


Select local groups to scan
================
Insert the local groups you would like to enumerate:
1. Administrators [Default]
2. Remote Desktop Users
3. Remote Management Users
4. Power Users
5. Backup Operator
6. Users
7. ...

> 1,2,4

***OUTPUT file structure***
Computer\tLocalGroupName\tSID\tAccount


Let me know what do you think, I will discuss with you privately before updating this as a PR.

**Comment by vletoux** [comment]
It adds to much complexity. Querying all the group take less time than just answering the menu...

**Comment by B1t0n** [comment]
Isn't the speed related to the amount of queried endpoints?
700 endpoints took a while for me.

**Pull request closed without merging**
