### PR TITLE
more typos fixed

### PR DESCRIPTION
**Pull request by ruppde**

### CODE REVIEW

**Comment by vletoux** [comment]
Thanks for submitting these changes
I can approve the sentences change in the rule description file.
but not the changes in the risk control file.
Indeed, the UI became awful (there is no new line in your change - did you tested it ?).

I'm proposing this change instead:
image

`<h2>Risk model <i class=""info-mark d-print-none has-tooltip"" data-bs-placement=""bottom"" data1-bs-toggle=""tooltip"" data-bs-html=""true"" title="""" data-bs-original-title=""Left-click on the headlines in the boxes for more details."">?</i></h2>`
 here: https://github.com/vletoux/pingcastle/blob/master/Report/ReportRiskControls.cs#L109

**Comment by ruppde** [comment]
sorry, didn't test it because I thought that new line would work right out of the box. but I showed the feature to colleague today, who has read numerous pingcastle -reports in the past. he was neither aware of the possibility to left click there and loved it :)

that help icon would help a bit, but the perfect solution would be make it visible in common UI terms, that the boxes are clickable, like underlined text for hyperlinks, or buttons. but that would probably look awful here. another good hint might be changing mouse pointer, if it's moved over the boxes. could be done like this:

https://www.tutorialrepublic.com/codelab.php?topic=faq&file=css-make-the-cursor-a-hand-pointer-on-hover

**Comment by vletoux** [comment]
I cannot accept this PR because the UI design change but the changes have been pushed with other commits

**Comment by vletoux** [comment]
Ok simply changed css:
image

pointer is now more visible

**Pull request closed without merging**
