### PR TITLE
Update ReportHealthCheckSingle.cs

### PR DESCRIPTION
**Pull request by moshekaplan**

### CODE REVIEW

**Comment by vletoux** [comment]
Thanks
The real code is on another report and is copy paste here at each release but I’ll port back the fix

**Comment by moshekaplan** [comment]
Do you want further typo corrections and the like to be submitted as PRs?

**Comment by vletoux** [comment]
Just send a file with the typo at support@pingcastle.com and I’ll fix them
Beware the next release is imminent so you have to do it within the current week

**Comment by moshekaplan** [comment]
OK, I will send as a git diff

**Pull request closed without merging**
